### ISSUE TITLE
Query string enums not serialized correctly in C# client

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/principle-studios-openapi-generators#127]
The C# client does not correctly convert enum values into their query string equivalents.

```
query_value:
  type: string
  enum:
    - Simple
    - Has Spaces
    - Has%Symbols
    - lower case
```

This is because a simple `global::System.Convert.ToString` is used for those types. Research to see if that can be overridden or provide a different mechanism.
