### ISSUE TITLE
Query string enums not deserialized correctly in C# MVC Server

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/principle-studios-openapi-generators#128]
The C# server does not correctly convert enum values from a query string.

```
query_value:
  type: string
  enum:
    - Simple
    - Has Spaces
    - Has%Symbols
    - lower case
```

Research to see if MVC query string deserialization can be overridden or provide a different mechanism.
