### ISSUE TITLE
TypeScript array model escapes inline objects

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/principle-studios-openapi-generators#42]
Typescript generates array component schemas incorrectly.

For the given yaml:

```
components:
  schemas:
    SomeArray:
      type: array
      items:
        type: object
        properties:
          id: { type: string }
```

Expected:

    Array<{ id?: string | null }>

Actual:

    Array&lt;{ id?: string | null }&gt;
