### ISSUE TITLE
Inline types nested inside of inline types do not get generated

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/principle-studios-openapi-generators#88]
Simple reproduction yaml:

``` yaml
component:
  schemas:
    Parent:
      type: object
      required: [ someProp ]
      properties:
        someProp:
          type: object
          # this object does not get generated, but will be referred to as `ParentSomeProp` within `Parent`
          required: [ inner ]
          properties:
            inner: { type: string }
```
